---
- name: provisioning django_messages testapp
  hosts: localhost
  connection: local
  vars:
    pip_run: "{{ lookup('ansible.builtin.env', 'PIP_INSTALLED', default='False') }}"
  tasks:
    - name: Create Pod
      containers.podman.podman_pod:
        name: django_forum_test_pod
        publish:
          - 8000:8000
          - 7900:7900
        state: started
    - name: Create volume if it doesn't exist
      containers.podman.podman_volume:
        name: certvol
        state: present
        recreate: true
    - name: Create Redis Container
      containers.podman.podman_container:
        name: redis_cont
        image: docker.io/library/redis
        command: redis-server --appendonly yes
        # state: created
        pod: django_forum_test_pod
    - name: Create Selenium Container
      containers.podman.podman_container:
        name: selen_cont
        image: docker.io/selenium/standalone-firefox:4.7.2-20221217
        shm_size: "2g"
        env:
          SE_SCREEN_WIDTH: 1920
          SE_SCREEN_HEIGHT: 1080
          SE_SCREEN_DEPTH: 24
          # state: created
        pod: django_forum_test_pod
    - name: Pull Python Image
      containers.podman.podman_image:
        name: docker.io/library/python
        state: present
    - name: Build Custom Python Image
      containers.podman.podman_image:
        name: python
        tag: django_forum_test_image
        path: ./dockerfile_python
        build:
          # cache: false
          extra_args: "-f './dockerfile_python/Dockerfile_Test'"
        state: present
      register: build_output
    - debug: var=build_output
    - name: output image info
      shell: exec {{ build_output['podman_actions'][0] }}
      register: image_output
    - debug: var=image_output.stdout_lines
    - name: Create custom container
      containers.podman.podman_container:
        name: django_forum_test_cont
        image: localhost/python:django_forum_test_image
        state: started
        detach: true
        recreate: false
        volume:
          - "{{ playbook_dir }}/../../../django_forum:/opt/ceramic_isles_test:Z"
          - "certvol:/etc/certs"
        pod: django_forum_test_pod
      register: output
    - debug: var=output
    - name: podman exec pip install
      shell: podman exec -it django_forum_test_cont bash -c '! pip show django &>/dev/null && 
          pip install -r /opt/ceramic_isles_test/django_forum/testapp/dockerfile_python/pip_requirements'
      register: pip_output
      # when: build_output.changed # 'pip_run|bool != True'
      tags: pip_install
    - debug: var=pip_output # .stdout_lines
    - name: test pytest output
      shell: echo '{{ output.stdout }}'
      register: test_output
    - debug: var=test_output.stdout_lines

