FROM docker.io/library/python:slim
ARG PROJECT_NAME="ceramic_isles_test"
ENV PYTHONPATH="/opt/${PROJECT_NAME}/"
RUN apt-get update && apt-get upgrade -y && apt --fix-broken install && apt-get install -y wget libmagic1 libmagickwand-dev libjpeg62-turbo-dev zlib1g-dev python3-pil python3-pil.imagetk graphviz graphviz-dev vim libnss3 gpg git default-libmysqlclient-dev && wget -q https://dl-ssl.google.com/linux/linux_signing_key.pub -O /etc/apt/trusted.gpg.d/googlekey.pub && cat /etc/apt/trusted.gpg.d/googlekey.pub | gpg --dearmor -o /etc/apt/trusted.gpg.d/googlekey.gpg && rm /etc/apt/trusted.gpg.d/googlekey.pub && gpg --import /etc/apt/trusted.gpg.d/googlekey.gpg && echo "deb [signed-by=/etc/apt/trusted.gpg.d/googlekey.gpg] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list && apt-get update && apt-get install google-chrome-stable -y && rm -rf /var/lib/apt/lists/* && mkdir -p /opt/${PROJECT_NAME} && mkdir -p /var/log/${PROJECT_NAME};
COPY skel/* /etc/skel
RUN useradd -m artisan -s /bin/bash && mkdir /home/artisan/django_venv && chown artisan:artisan /opt/${PROJECT_NAME} /var/log/${PROJECT_NAME} /home/artisan/django_venv
ENV VIRTUAL_ENV=/home/artisan/django_venv
RUN su artisan -c "python3 -m venv $VIRTUAL_ENV"
ENV PATH=$VIRTUAL_ENV/bin:$PATH
COPY ./pip_requirements /tmp/pip_requirements
RUN chmod o+r /tmp/pip_requirements && su artisan -c ". /home/artisan/django_venv/bin/activate && python -m pip install --upgrade pip wheel && pip install --no-cache-dir -r /tmp/pip_requirements" && rm -r /tmp/pip_requirements
COPY ./docker_entrypoint_init.sh /docker_entrypoint_init.sh
USER artisan
ENTRYPOINT ["/docker_entrypoint_init.sh"]