---
- name: provisioning django_forum testapp
  hosts: localhost
  tasks:
  - name: Remove Pod
    containers.podman.podman_pod:
      name: django_forum_test_pod
      state: absent
  # - name: Remove Database
  #   shell: rm ../db.sqlite3
  #   register: output
  # - debug: var=output.stdout_lines
