# build command is: podman build --tag='python:django' -f='dockerfile_django'
FROM docker.io/library/python
ARG PROJECT_NAME="ceramic_isles_test"
ENV PYTHONPATH="/opt/${PROJECT_NAME}/"
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y libmagic1 libmagickwand-dev libjpeg62-turbo-dev zlib1g-dev python3-pil python3-pil.imagetk graphviz graphviz-dev vim
RUN rm -rf /var/lib/apt/lists/*
RUN mkdir -p /opt/${PROJECT_NAME};
RUN mkdir -p /var/log/${PROJECT_NAME};
COPY skel/* /etc/skel
ENTRYPOINT ["/opt/ceramic_isles_test/django_forum/testapp/dockerfile_python/docker_entrypoint_init.sh"]